




from common.enums.enum_base import EnumBase


class AppConfigEnum(str,EnumBase):
    """Enumeration for APP configurations, either in server or config files section
        FIRST SECTION ARE CONFIG KEYS IN SERVER DDBB
        SECOND SECTION ARE CONFIG KEYS IN CONFIG FILE SO WE USE CFG_ PREFIX
    """  
    AUTH_CONFIG="AUTH_CONFIG",  
    ANGULAR_CONFIG="ANGULAR_CONFIG",
    CHANGE_EMAIL_CONFIG="CHANGE_EMAIL_CONFIG",
    FARGATE_TASKS_CONFIG="FARGATE_TASKS_CONFIG",
    LAMBDA_CONFIG="LAMBDA_CONFIG",
    GIS_SERVER_CONFIG="GIS_SERVER_CONFIG",
    QUEUE_EMAIL_CONFIG="QUEUE_EMAIL_CONFIG",
    QUEUE_NOTIFICATIONS_CONFIG="QUEUE_NOTIFICATIONS_CONFIG"
    RESET_EMAIL_CONFIG="RESET_EMAIL_CONFIG",
    EMAIL_INFO_CONFIG="EMAIL_INFO_CONFIG",
    
    REPOSITORY_CONFIG="REPOSITORY_CONFIG",
    WEB_SOCKET_CONFIG="WEB_SOCKET_CONFIG",

    CFG_AUTH_CONFIG="token",
    CFG_FARGATE_TASKS_CONFIG="fargate_tasks" ,
    CFG_REPOSITORY="repository",
    CFG_QUEUE_EMAIL_CONFIG="queue_email",
    CFG_QUEUE_NOTIFICATIONS_CONFIG="notifications_queue"      

    
    


    
